# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9602d19268aa623ec7e80cd1af9977ec44829d82137b74ec497d8a82df768ed5a216b0794e96c35344a47b6023e9fd26dd28422b9bc00bd7899a3e758a4126cb

test:
  secret_key_base: 75549c190861d17cbda4e0a15a8fce01866225962e71cd6f23a4eeb3047592ba6e2c2e13707e94564f7384f9201ce52c613d83308f15938ba3aa4ebec30056e9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
